version: "3"
services:
  app:
    build: ./app
    links:
      - db
    command: gunicorn --bind 0.0.0.0:5000 app:app
    ports:
      - "5000:5000"

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./mysql:/var/lib/mysql

  nginx:
    build: ./nginx
    restart: always
    links:
      - app
    ports:
      - "80:80"
    volumes:
      - ./logs:/var/log/nginx
